import type { EvidenceSource } from '../types';

export const evidenceSources = {
  notionMigrationIndex: {
    id: 'src-notion-dpas-migration-index',
    label: 'Notion Dpas-migration index',
    path: 'Dpas-migration',
    commitHash: 'notion-2026-05-23-index',
    commitDate: '2026-05-23',
    commitTitle: 'Dpas-migration project index',
    note: 'Part 1 build loop부터 Part 9 final report까지 이어지는 migration roadmap입니다.',
  },
  notionPart1BuildLoop: {
    id: 'src-notion-part1-build-loop',
    label: 'Notion Part 1 - Kernel build/boot loop',
    path: 'Dpas-migration Part 1',
    commitHash: 'notion-2026-05-20-part1',
    commitDate: '2026-05-20',
    commitTitle: 'Part 1 - Kernel Build Boot Loop',
    note: 'DPAS 구현 전에 kernel 수정, 빌드, 부팅 또는 compile check, 로그 확인, 복구 루프를 닫는 준비 단계입니다.',
  },
  notionStep1: {
    id: 'src-notion-step1-polled-io',
    label: 'Notion Part 3 Step 1 - Polled I/O path note',
    path: 'Dpas-migration Part 3 / 2026-05-23 Step 1',
    commitHash: 'notion-2026-05-23-step1',
    commitDate: '2026-05-23',
    commitTitle: 'Step 1 - Polled I/O Path 코드 리딩 노트',
    note: 'submit path와 poll path, bi_cookie/tag/hctx 관계, PAS hook 후보를 쉽게 풀어쓴 Step 1 노트입니다.',
  },
  notionStep2: {
    id: 'src-notion-step2-req-polled-submit',
    label: 'Notion Part 3 Step 2 - REQ_POLLED submission note',
    path: 'Dpas-migration Part 3 / 2026-05-24 Step 2',
    commitHash: 'notion-2026-05-24-step2',
    commitDate: '2026-05-24',
    commitTitle: 'Step 2 - REQ_POLLED 설정 지점 코드 리딩 노트',
    note: 'RWF_HIPRI, IOCB_HIPRI, bio->bi_opf, request->cmd_flags, HCTX_TYPE_POLL, DPAS 5.18 interrupt-mode 비교를 정리한 Step 2 노트입니다.',
  },
  notionStep3: {
    id: 'src-notion-step3-queue-hooks',
    label: 'Notion Part 3 Step 3 - Queue Mapping and DPAS hook note',
    path: 'Dpas-migration Part 3 / 2026-05-25 Step 3',
    commitHash: 'notion-2026-05-25-step3',
    commitDate: '2026-05-25',
    commitTitle: 'Step 3 - Queue Mapping + DPAS 5.18 Hook 추출 노트',
    note: '최신 HCTX_TYPE_POLL/NVMe poll queue foundation과 DPAS 5.18의 PAS state, sleep-before-poll, result update, fops.c interrupt hook을 분리한 노트입니다.',
  },
  notionPart2: {
    id: 'src-notion-part2-paper-model',
    label: 'Notion Part 2 - DPAS paper model',
    path: 'Dpas-migration Part 2',
    commitHash: 'notion-2026-05-20-part2',
    commitDate: '2026-05-20',
    commitTitle: 'Part 2 - DPAS 논문 구조 이해',
    note: 'Figure 1/3/7/9/10을 migration hook 후보로 변환하는 기준 문서입니다.',
  },
  notionPart3: {
    id: 'src-notion-part3-polling-path',
    label: 'Notion Part 3 - latest polling path',
    path: 'Dpas-migration Part 3',
    commitHash: 'notion-2026-05-23-part3',
    commitDate: '2026-05-23',
    commitTitle: 'Part 3 - 최신 Linux blk-mq/NVMe Polling Path 코드 리딩',
    note: 'bio_poll, blk_mq_poll, blk_hctx_poll, nvme_poll 흐름을 읽는 기준 문서입니다.',
  },
  notionPart4: {
    id: 'src-notion-part4-minimal-pas',
    label: 'Notion Part 4 - Minimal PAS-only port',
    path: 'Dpas-migration Part 4',
    commitHash: 'notion-2026-05-20-part4',
    commitDate: '2026-05-20',
    commitTitle: 'Part 4 - Minimal PAS-only 포팅 계획',
    note: 'PAS sleep-before-poll 최소 포팅 계획입니다.',
  },
  notionPart5: {
    id: 'src-notion-part5-mode-switching',
    label: 'Notion Part 5 - DPAS mode switching',
    path: 'Dpas-migration Part 5',
    commitHash: 'notion-2026-05-20-part5',
    commitDate: '2026-05-20',
    commitTitle: 'Part 5 - DPAS Mode Switching 포팅 계획',
    note: 'CP/PAS normal/PAS overloaded/Interrupt state machine 포팅 계획입니다.',
  },
  notionPart6: {
    id: 'src-notion-part6-interrupt-mode',
    label: 'Notion Part 6 - Interrupt mode and NVMe mapping',
    path: 'Dpas-migration Part 6',
    commitHash: 'notion-2026-05-20-part6',
    commitDate: '2026-05-20',
    commitTitle: 'Part 6 - Full Interrupt Mode & NVMe Queue Mapping',
    note: 'submission-side REQ_POLLED 제어와 NVMe queue mapping 검증 계획입니다.',
  },
  notionPart7: {
    id: 'src-notion-part7-fio-validation',
    label: 'Notion Part 7 - FIO validation',
    path: 'Dpas-migration Part 7',
    commitHash: 'notion-2026-05-20-part7',
    commitDate: '2026-05-20',
    commitTitle: 'Part 7 - FIO Microbenchmark & DPAS 성능 검증 계획',
    note: 'FIO 기반 microbenchmark와 mode breakdown 검증 계획입니다.',
  },
  localKernel: {
    id: 'src-local-linux-upstream',
    label: 'DPAS_FAST26 kernel source',
    path: '/home/clip968/DPAS_FAST26/src/linux-upstream and kernel artifacts',
    commitHash: 'kernel-local-dpas-fast26',
    commitDate: '2026-05-23',
    commitTitle: 'Local kernel trees used for migration reading',
    note: '최신 upstream path와 5.18 artifact hook extraction을 비교할 기준입니다.',
  },
} satisfies Record<string, EvidenceSource>;
