import type { GraphEdge } from './types';

export const graphEdges: GraphEdge[] = [
  { id: 'e-root-build-loop', source: 'repo-overview', target: 'part1-build-boot-loop', label: '작업 루프 준비', kind: '이해 필요' },
  { id: 'e-build-loop-submit', source: 'part1-build-boot-loop', target: 'path-submit-polled', label: '빌드 루프 이후 코드 리딩', kind: '마이그레이션' },
  { id: 'e-root-completion-model', source: 'repo-overview', target: 'kernel-io-completion-model', label: '전체 문제 정의', kind: '이해 필요' },
  { id: 'e-root-blk-mq', source: 'repo-overview', target: 'concept-blk-mq', label: 'kernel 중심축', kind: '이해 필요' },
  { id: 'e-root-submit', source: 'repo-overview', target: 'path-submit-polled', label: 'I/O 제출 경로', kind: '이해 필요' },
  { id: 'e-root-poll', source: 'repo-overview', target: 'path-poll-completion', label: '완료 확인 경로', kind: '이해 필요' },
  { id: 'e-completion-req-polled', source: 'kernel-io-completion-model', target: 'concept-req-polled', label: 'polled I/O 표시', kind: '이해 필요' },
  { id: 'e-blk-mq-bio', source: 'concept-blk-mq', target: 'concept-bio', label: '입력 I/O 단위', kind: '이해 필요' },
  { id: 'e-blk-mq-request', source: 'concept-blk-mq', target: 'concept-request', label: 'driver 제출 단위', kind: '이해 필요' },
  { id: 'e-blk-mq-hctx', source: 'concept-blk-mq', target: 'concept-hctx', label: 'hardware queue context', kind: '이해 필요' },
  { id: 'e-blk-mq-ctx', source: 'concept-blk-mq', target: 'concept-ctx', label: 'software queue context', kind: '이해 필요' },
  { id: 'e-blk-mq-mq-ops', source: 'concept-blk-mq', target: 'concept-mq-ops', label: 'driver callback', kind: '이해 필요' },
  { id: 'e-ctx-hctx', source: 'concept-ctx', target: 'concept-hctx', label: 'ctx->hctxs[]', kind: '코드 흐름' },
  { id: 'e-mq-ops-nvme-poll', source: 'concept-mq-ops', target: 'function-nvme-poll', label: 'mq_ops->poll()', kind: '코드 흐름' },
  { id: 'e-mq-ops-start-req', source: 'concept-mq-ops', target: 'function-blk-mq-start-request', label: 'issue 전 block layer', kind: '코드 흐름' },
  { id: 'e-completion-interrupt', source: 'kernel-io-completion-model', target: 'path-interrupt-completion', label: 'IRQ completion', kind: '이해 필요' },
  { id: 'e-completion-poll', source: 'kernel-io-completion-model', target: 'path-poll-completion', label: 'polled completion', kind: '이해 필요' },
  { id: 'e-req-polled-iopoll', source: 'concept-req-polled', target: 'path-io-uring-iopoll', label: 'io_uring 진입', kind: '코드 흐름' },
  { id: 'e-iopoll-step2', source: 'path-io-uring-iopoll', target: 'step2-req-polled-submission', label: 'RWF/IOCB_HIPRI 진입', kind: '코드 흐름' },
  { id: 'e-step2-map-kiocb', source: 'step2-req-polled-submission', target: 'step2-kiocb-hipri', label: 'signal card', kind: '이해 필요' },
  { id: 'e-step2-kiocb-flow', source: 'step2-kiocb-hipri', target: 'step2-flag-propagation', label: 'IOCB_HIPRI gate', kind: '코드 흐름' },
  { id: 'e-step2-flow-req-polled', source: 'step2-flag-propagation', target: 'concept-req-polled', label: 'bio/request flag', kind: '코드 흐름' },
  { id: 'e-step2-flow-submit', source: 'step2-flag-propagation', target: 'path-submit-polled', label: 'submit-side 결정', kind: '코드 흐름' },
  { id: 'e-step2-flow-start-req', source: 'step2-flag-propagation', target: 'function-blk-mq-start-request', label: 'cookie 저장', kind: '코드 흐름' },
  { id: 'e-step2-flow-compare', source: 'step2-flag-propagation', target: 'step2-dpas-518-comparison', label: 'DPAS 차이', kind: '증거' },
  { id: 'e-step2-step3-overview', source: 'step2-flag-propagation', target: 'step3-overview', label: 'queue mapping으로 확장', kind: '코드 흐름' },
  { id: 'e-step2-compare-risk', source: 'step2-dpas-518-comparison', target: 'risk-interrupt-submission', label: 'true IRQ mode 근거', kind: '리스크' },
  { id: 'e-step2-compare-hooks', source: 'step2-dpas-518-comparison', target: 'step2-hook-candidates', label: 'submission hook 도출', kind: '마이그레이션' },
  { id: 'e-step2-hooks-part6', source: 'step2-hook-candidates', target: 'part6-interrupt-mode', label: 'hook 후보', kind: '마이그레이션' },
  { id: 'e-step3-overview-queue', source: 'step3-overview', target: 'step3-queue-mapping-foundation', label: '최신 queue foundation', kind: '이해 필요' },
  { id: 'e-step3-queue-nvme', source: 'step3-queue-mapping-foundation', target: 'step3-nvme-poll-queue-map', label: 'driver queue map', kind: '코드 흐름' },
  { id: 'e-step3-nvme-hooks', source: 'step3-nvme-poll-queue-map', target: 'step3-dpas-518-hook-inventory', label: '5.18 policy 대조', kind: '증거' },
  { id: 'e-step3-hooks-state', source: 'step3-dpas-518-hook-inventory', target: 'step3-pas-state-duration', label: 'PAS state', kind: '코드 흐름' },
  { id: 'e-step3-state-loop', source: 'step3-pas-state-duration', target: 'step3-pas-sleep-update-loop', label: 'feedback loop', kind: '코드 흐름' },
  { id: 'e-step3-hooks-fops', source: 'step3-dpas-518-hook-inventory', target: 'step3-dpas-interrupt-fops-hook', label: 'full DPAS hook', kind: '코드 흐름' },
  { id: 'e-step3-loop-boundary', source: 'step3-pas-sleep-update-loop', target: 'step3-part4-boundary', label: 'Part 4 포함', kind: '마이그레이션' },
  { id: 'e-step3-fops-boundary', source: 'step3-dpas-interrupt-fops-hook', target: 'step3-part4-boundary', label: 'Part 4 제외', kind: '마이그레이션' },
  { id: 'e-step3-boundary-step4', source: 'step3-part4-boundary', target: 'step4-overview', label: 'diff decision으로 넘김', kind: '이해 필요' },
  { id: 'e-step3-boundary-part4', source: 'step3-part4-boundary', target: 'part4-minimal-pas', label: 'PAS-only 시작', kind: '마이그레이션' },
  { id: 'e-step3-fops-part6', source: 'step3-dpas-interrupt-fops-hook', target: 'part6-interrupt-mode', label: 'submission hook 증거', kind: '검증 근거' },
  { id: 'e-step3-queue-risk', source: 'step3-queue-mapping-foundation', target: 'risk-interrupt-submission', label: 'poll hctx 선결정', kind: '리스크' },
  { id: 'e-step3-fops-risk', source: 'step3-dpas-interrupt-fops-hook', target: 'risk-interrupt-submission', label: 'REQ_POLLED 제거 필요', kind: '정정' },
  { id: 'e-step4-overview-state', source: 'step4-overview', target: 'step4-state-placement', label: 'state 위치를 좁힘', kind: '이해 필요' },
  { id: 'e-step4-overview-hook', source: 'step4-overview', target: 'step4-poll-hook-candidates', label: 'poll hook을 비교', kind: '이해 필요' },
  { id: 'e-step4-overview-lifecycle', source: 'step4-overview', target: 'step4-queue-lifecycle', label: 'init/free를 요구', kind: '이해 필요' },
  { id: 'e-step4-state-sysfs', source: 'step4-state-placement', target: 'step4-sysfs-lifecycle', label: 'NULL guard를 요구', kind: '코드 흐름' },
  { id: 'e-step4-lifecycle-sysfs', source: 'step4-queue-lifecycle', target: 'step4-sysfs-lifecycle', label: 'safe show/store를 가능하게 함', kind: '코드 흐름' },
  { id: 'e-step4-lifecycle-q-model', source: 'step4-queue-lifecycle', target: 'step4-request-queue-model', label: 'q 구조를 설명', kind: '이해 필요' },
  { id: 'e-step4-q-model-hctx-type', source: 'step4-request-queue-model', target: 'step4-hctx-type-init-map', label: 'type map을 해석', kind: '코드 흐름' },
  { id: 'e-step4-hctx-hook', source: 'step4-hctx-type-init-map', target: 'step4-poll-hook-candidates', label: 'POLL 대상임을 증명', kind: '코드 흐름' },
  { id: 'e-step4-hook-questions', source: 'step4-poll-hook-candidates', target: 'step4-open-questions', label: 'request gap을 남김', kind: '미해결' },
  { id: 'e-step4-state-questions', source: 'step4-state-placement', target: 'step4-open-questions', label: 'allocation 정책을 남김', kind: '미해결' },
  { id: 'e-step4-questions-part4', source: 'step4-open-questions', target: 'part4-minimal-pas', label: 'Part 4 patch로 넘김', kind: '마이그레이션' },
  { id: 'e-step4-hook-pas', source: 'step4-poll-hook-candidates', target: 'concept-pas-sleep-before-poll', label: 'PAS hook 후보를 좁힘', kind: '논문 대응' },
  { id: 'e-step4-blk-mq-poll-hook', source: 'function-blk-mq-poll', target: 'step4-poll-hook-candidates', label: 'cookie lookup 근거를 제공', kind: '코드 흐름' },
  { id: 'e-foundation-blk-mq-step4-q', source: 'concept-blk-mq', target: 'step4-request-queue-model', label: 'request_queue 확장 판단', kind: '이해 필요' },
  { id: 'e-foundation-hctx-step4-map', source: 'concept-hctx', target: 'step4-hctx-type-init-map', label: 'hctx type map 재사용', kind: '코드 흐름' },
  { id: 'e-step4-pas-state-placement', source: 'step3-pas-state-duration', target: 'step4-state-placement', label: 'state 분리를 요구', kind: '마이그레이션' },
  { id: 'e-step4-hctx-interrupt-risk', source: 'step4-hctx-type-init-map', target: 'risk-interrupt-submission', label: 'REQ_POLLED 우선을 정정', kind: '리스크' },
  { id: 'e-iopoll-bio-poll', source: 'path-io-uring-iopoll', target: 'function-bio-poll', label: 'iocb_bio_iopoll', kind: '코드 흐름' },
  { id: 'e-submit-start-req', source: 'path-submit-polled', target: 'function-blk-mq-start-request', label: 'cookie 저장', kind: '코드 흐름' },
  { id: 'e-start-req-cookie', source: 'function-blk-mq-start-request', target: 'concept-bi-cookie-tag', label: 'bi_cookie WRITE_ONCE', kind: '코드 흐름' },
  { id: 'e-interrupt-mq-ops', source: 'path-interrupt-completion', target: 'concept-mq-ops', label: 'mq_ops->complete()', kind: '코드 흐름' },
  { id: 'e-interrupt-risk-path', source: 'path-interrupt-completion', target: 'risk-interrupt-submission', label: 'submit-side 대조', kind: '리스크' },
  { id: 'e-bio-req-polled', source: 'concept-bio', target: 'concept-req-polled', label: 'bio flag', kind: '코드 흐름' },
  { id: 'e-bio-request', source: 'concept-bio', target: 'concept-request', label: 'bio -> request 변환', kind: '코드 흐름' },
  { id: 'e-request-hctx', source: 'concept-request', target: 'concept-hctx', label: 'selected hctx', kind: '이해 필요' },
  { id: 'e-req-polled-hctx', source: 'concept-req-polled', target: 'concept-hctx', label: 'HCTX_TYPE_POLL 선택', kind: '코드 흐름' },
  { id: 'e-hctx-cookie', source: 'concept-hctx', target: 'concept-bi-cookie-tag', label: 'hctx queue_num 저장', kind: '오해 방지' },
  { id: 'e-submit-cookie', source: 'path-submit-polled', target: 'concept-bi-cookie-tag', label: 'blk_mq_start_request()', kind: '코드 흐름' },
  { id: 'e-submit-poll', source: 'path-submit-polled', target: 'path-poll-completion', label: 'bi_cookie로 연결', kind: '이해 필요' },
  { id: 'e-poll-bio-poll', source: 'path-poll-completion', target: 'function-bio-poll', label: 'poll entry', kind: '코드 흐름' },
  { id: 'e-bio-poll-blk-mq-poll', source: 'function-bio-poll', target: 'function-blk-mq-poll', label: 'cookie 전달', kind: '코드 흐름' },
  { id: 'e-blk-mq-poll-hctx-poll', source: 'function-blk-mq-poll', target: 'function-blk-hctx-poll', label: 'hctx poll', kind: '코드 흐름' },
  { id: 'e-hctx-poll-nvme', source: 'function-blk-hctx-poll', target: 'function-nvme-poll', label: 'mq_ops->poll()', kind: '코드 흐름' },
  { id: 'e-cookie-bio-poll', source: 'concept-bi-cookie-tag', target: 'function-bio-poll', label: 'cookie를 읽음', kind: '오해 방지' },
  { id: 'e-cookie-blk-mq-poll', source: 'concept-bi-cookie-tag', target: 'function-blk-mq-poll', label: 'q->queue_hw_ctx[cookie]', kind: '오해 방지' },
  { id: 'e-figure-pas-hook', source: 'paper-pas-core', target: 'concept-pas-sleep-before-poll', label: '논문 PAS -> kernel hook', kind: '논문 대응' },
  { id: 'e-pas-part4', source: 'concept-pas-sleep-before-poll', target: 'part4-minimal-pas', label: '최소 포팅 대상', kind: '마이그레이션' },
  { id: 'e-pas-step3-loop', source: 'concept-pas-sleep-before-poll', target: 'step3-pas-sleep-update-loop', label: '5.18 구현 근거', kind: '증거' },
  { id: 'e-poll-pas-hook', source: 'path-poll-completion', target: 'concept-pas-sleep-before-poll', label: 'hook 후보', kind: '이해 필요' },
  { id: 'e-bio-poll-pas-hook', source: 'function-bio-poll', target: 'concept-pas-sleep-before-poll', label: '후보 #1', kind: '미해결' },
  { id: 'e-blk-mq-poll-pas-hook', source: 'function-blk-mq-poll', target: 'concept-pas-sleep-before-poll', label: '후보 #2', kind: '미해결' },
  { id: 'e-hctx-poll-cpu-relax', source: 'function-blk-hctx-poll', target: 'mis-cpu-relax-sleep', label: 'sleep 아님', kind: '오해 방지' },
  { id: 'e-figure-dpas-mode', source: 'paper-dpas-state-machine', target: 'concept-dpas-mode', label: '논문 state machine', kind: '논문 대응' },
  { id: 'e-dpas-mode-interrupt-risk', source: 'concept-dpas-mode', target: 'risk-interrupt-submission', label: 'interrupt mode 한계', kind: '리스크' },
  { id: 'e-dpas-mode-fops-hook', source: 'concept-dpas-mode', target: 'step3-dpas-interrupt-fops-hook', label: '5.18 interrupt enforcement', kind: '증거' },
  { id: 'e-req-polled-interrupt-risk', source: 'concept-req-polled', target: 'risk-interrupt-submission', label: 'future I/O 제어', kind: '리스크' },
  { id: 'e-submit-interrupt-risk', source: 'path-submit-polled', target: 'risk-interrupt-submission', label: 'submission-side 문제', kind: '리스크' },
  { id: 'e-submit-mis', source: 'path-submit-polled', target: 'mis-submit-vs-poll', label: '경로 구분', kind: '오해 방지' },
  { id: 'e-poll-mis', source: 'path-poll-completion', target: 'mis-submit-vs-poll', label: '경로 구분', kind: '오해 방지' },
  { id: 'e-part4-mode', source: 'part4-minimal-pas', target: 'concept-dpas-mode', label: 'Part 5로 확장', kind: '마이그레이션' },
  { id: 'e-part4-part5', source: 'part4-minimal-pas', target: 'part5-mode-switching', label: '다음 milestone', kind: '마이그레이션' },
  { id: 'e-part5-mode', source: 'part5-mode-switching', target: 'concept-dpas-mode', label: 'state machine 구현', kind: '마이그레이션' },
  { id: 'e-part5-part6', source: 'part5-mode-switching', target: 'part6-interrupt-mode', label: 'IRQ mode 검증', kind: '마이그레이션' },
  { id: 'e-part6-risk', source: 'part6-interrupt-mode', target: 'risk-interrupt-submission', label: 'submission proof', kind: '검증 근거' },
  { id: 'e-part6-validation', source: 'part6-interrupt-mode', target: 'part7-validation', label: 'FIO counter', kind: '검증 근거' },
  { id: 'e-mode-validation', source: 'concept-dpas-mode', target: 'part7-validation', label: 'mode counter 검증', kind: '검증 근거' },
  { id: 'e-interrupt-validation', source: 'risk-interrupt-submission', target: 'part7-validation', label: 'FIO로 관찰', kind: '검증 근거' },
  { id: 'e-step4-direct-current', source: 'step4-state-placement', target: 'dpas-71-mode-switching-direct-fields', label: '현재 구현 상태', kind: '정정' },
  { id: 'e-direct-sysfs-reset', source: 'dpas-71-mode-switching-direct-fields', target: 'step4-sysfs-lifecycle', label: 'state window reset', kind: '코드 흐름' },
  { id: 'e-direct-submit-helper', source: 'dpas-71-mode-switching-direct-fields', target: 'dpas-71-submit-helper', label: 'mode를 submit에서 읽음', kind: '코드 흐름' },
  { id: 'e-submit-helper-interrupt-risk', source: 'dpas-71-submit-helper', target: 'risk-interrupt-submission', label: 'REQ_POLLED 제거', kind: '정정' },
  { id: 'e-submit-helper-part6', source: 'dpas-71-submit-helper', target: 'part6-interrupt-mode', label: '현재 submit hook', kind: '마이그레이션' },
  { id: 'e-direct-static-test', source: 'dpas-71-mode-switching-direct-fields', target: 'validation-full-mode-static-test', label: '구조 검증', kind: '검증 근거' },
  { id: 'e-submit-static-test', source: 'dpas-71-submit-helper', target: 'validation-full-mode-static-test', label: 'helper 검증', kind: '검증 근거' },
  { id: 'e-static-open-runtime', source: 'validation-full-mode-static-test', target: 'step4-open-questions', label: 'runtime은 남음', kind: '미해결' },
  { id: 'e-colima-open-boot', source: 'validation-colima-build-loop', target: 'step4-open-questions', label: 'boot 검증 남음', kind: '미해결' },
  { id: 'e-optane-validation', source: 'validation-optane-knob-reset', target: 'part7-validation', label: '측정 조건 고정', kind: '검증 근거' },
  { id: 'e-optane-open-runtime', source: 'validation-optane-knob-reset', target: 'step4-open-questions', label: 'mode evidence 필요', kind: '미해결' },
];
