import type { CardDraft } from '../types';
import { communitySlot } from '../layout';
import { interruptRiskVisual, modeVisual, paperDpasVisual, paperPasVisual, part4Visual, part5Visual, part6Visual, pasSleepVisual } from '../visuals';

export const dpasPolicyCards: CardDraft[] = [
  {
    id: 'concept-pas-sleep-before-poll',
    kind: '개념',
    status: '검증 필요',
    community: 'dpas-policy',
    title: 'PAS sleep-before-poll',
    shortTitle: 'PAS hook',
    summary: 'poll 전에 짧게 sleep하여 CPU busy polling 비용을 줄이는 핵심 아이디어입니다.',
    position: communitySlot('dpas-policy', 1, 0),
    sourceKeys: ['notionPart2', 'notionPart4'],
    visual: pasSleepVisual,
    plain: 'PAS는 completion queue를 계속 바쁘게 확인하기 전에 잠깐 쉬는 방식입니다.',
    why: 'DPAS migration의 최소 구현 단위는 이 sleep-before-poll hook을 올바른 위치에 넣는 것입니다.',
    context: 'Part 4 Minimal PAS-only port의 중심입니다.',
  },
  {
    id: 'concept-dpas-mode',
    kind: '개념',
    status: '검증 필요',
    community: 'dpas-policy',
    title: 'DPAS mode switching',
    shortTitle: 'DPAS mode',
    summary: '부하 상태에 따라 CP/PAS/Interrupt 계열 모드를 바꾸는 정책입니다.',
    position: communitySlot('dpas-policy', 1, 1),
    sourceKeys: ['notionPart2', 'notionPart5'],
    visual: modeVisual,
    plain: 'DPAS는 하나의 sleep 값이 아니라 상태에 따라 polling policy를 바꾸는 구조입니다.',
    why: 'Minimal PAS가 된 뒤 full DPAS로 가려면 mode counter와 transition reason이 필요합니다.',
    context: 'Part 5와 논문 Figure 10을 연결합니다.',
  },
  {
    id: 'risk-interrupt-submission',
    kind: '미해결',
    status: '검증 필요',
    community: 'dpas-policy',
    title: 'Interrupt mode requires submission-side proof',
    shortTitle: 'interrupt risk',
    summary: 'true interrupt mode는 poll skip만으로 충분하지 않고 REQ_POLLED/queue selection 확인이 필요합니다.',
    position: communitySlot('dpas-policy', 3, 1),
    sourceKeys: ['notionPart6'],
    visual: interruptRiskVisual,
    plain: '이미 polled queue로 제출된 I/O를 completion path에서만 skip하면 true interrupt mode라고 보기 어렵습니다.',
    why: 'DPAS mode switching 구현에서 가장 큰 설계 리스크입니다.',
    context: 'Part 6 Full Interrupt Mode & NVMe Queue Mapping의 핵심 질문입니다.',
  },
  {
    id: 'part4-minimal-pas',
    kind: '사건',
    status: '잠정',
    community: 'dpas-policy',
    title: 'Part 4 Minimal PAS-only port',
    shortTitle: 'Part 4 PAS',
    summary: '먼저 PAS sleep-before-poll만 최신 kernel에 이식하는 단계입니다.',
    position: communitySlot('dpas-policy', 2, 0),
    sourceKeys: ['notionPart4'],
    visual: part4Visual,
    plain: 'Part 4는 full DPAS 전에 최소 PAS hook을 닫는 단계입니다.',
    why: '첫 구현 범위를 줄여야 hook 위치와 latency impact를 검증할 수 있습니다.',
    context: 'DPAS migration의 첫 구현 milestone입니다.',
  },
  {
    id: 'part5-mode-switching',
    kind: '사건',
    status: '잠정',
    community: 'dpas-policy',
    title: 'Part 5 DPAS Mode Switching',
    shortTitle: 'Part 5 mode',
    summary: 'PAS-only 위에 CP/PAS/IRQ state machine과 UNDER/OVER update를 올리는 단계입니다.',
    position: communitySlot('dpas-policy', 2, 1),
    sourceKeys: ['notionPart5', 'notionPart2'],
    visual: part5Visual,
    plain: 'Part 5는 고정 sleep_ns를 workload 적응형 DPAS policy로 확장합니다.',
    why: 'Minimal PAS와 full DPAS를 분리하지 않으면 mode transition 버그 원인을 찾기 어렵습니다.',
    context: 'Figure 10 state machine 포팅과 mode counter/trace가 핵심 산출물입니다.',
  },
  {
    id: 'part6-interrupt-mode',
    kind: '사건',
    status: '잠정',
    community: 'dpas-policy',
    title: 'Part 6 Full Interrupt Mode',
    shortTitle: 'Part 6 IRQ',
    summary: 'interrupt mode 전환 시 REQ_POLLED/queue mapping/NVMe poll queue를 submission-side에서 검증합니다.',
    position: communitySlot('dpas-policy', 4, 1),
    sourceKeys: ['notionPart6', 'localKernel'],
    visual: part6Visual,
    plain: 'Part 6는 true interrupt mode가 submit부터 IRQ queue로 가는지 증명하는 단계입니다.',
    why: 'completion path skip만으로는 interrupt risk 카드의 질문을 닫을 수 없습니다.',
    context: 'drivers/nvme/host/pci.c queue mapping과 REQ_POLLED counter/trace가 필요합니다.',
  },
  {
    id: 'paper-pas-core',
    kind: '개념',
    status: '잠정',
    community: 'dpas-policy',
    title: 'DPAS paper PAS core',
    shortTitle: 'paper PAS',
    summary: '논문의 PAS 아이디어를 kernel polling path의 hook 후보로 바꿔 읽는 카드입니다.',
    position: communitySlot('dpas-policy', 0, 0),
    sourceKeys: ['notionPart2'],
    visual: paperPasVisual,
    plain: '논문 PAS는 polling 비용을 줄이기 위해 poll 전에 쉬는 아이디어입니다.',
    why: '논문 figure를 코드 위치로 번역하는 bridge가 필요합니다.',
    context: 'Part 2 Figure 1/3/7/9 논의와 Part 4 hook 계획 사이입니다.',
  },
  {
    id: 'paper-dpas-state-machine',
    kind: '개념',
    status: '잠정',
    community: 'dpas-policy',
    title: 'DPAS paper state machine',
    shortTitle: 'paper DPAS',
    summary: '논문 Figure 10의 state machine을 kernel mode switching 설계로 번역합니다.',
    position: communitySlot('dpas-policy', 0, 1),
    sourceKeys: ['notionPart2', 'notionPart5'],
    visual: paperDpasVisual,
    plain: 'DPAS state machine은 부하 상태에 따라 polling policy를 바꾸는 모델입니다.',
    why: '이 모델이 있어야 PAS-only에서 full DPAS로 넘어갈 수 있습니다.',
    context: 'Part 5 mode switching과 Part 6 interrupt risk의 논문 쪽 출발점입니다.',
  },
];
