import type { CardDraft } from '../types';
import { communitySlot } from '../layout';
import { bioVisual, blkMqStructureVisual, completionModelVisual, cookieTagVisual, ctxVisual, hctxVisual, mqOpsVisual, reqPolledVisual, requestVisual } from '../visuals';

export const foundationCards: CardDraft[] = [
  {
    id: 'kernel-io-completion-model',
    kind: '개념',
    status: '잠정',
    community: 'foundation',
    title: 'Kernel I/O completion model',
    shortTitle: 'completion model',
    summary: 'I/O 완료를 interrupt로 받을지, poll로 직접 확인할지 나누는 큰 모델입니다.',
    position: communitySlot('foundation', 0, 0),
    sourceKeys: ['notionPart3', 'localKernel'],
    visual: completionModelVisual,
    plain: '완료 확인 방식은 interrupt completion과 polled completion으로 나뉩니다.',
    why: 'DPAS는 polling 비용을 줄이려는 연구라 completion model 이해가 출발점입니다.',
    context: 'Part 3 polling path, Part 6 interrupt mode 논의의 상위 개념입니다.',
  },
  {
    id: 'concept-blk-mq',
    kind: '개념',
    status: '잠정',
    community: 'foundation',
    title: 'blk-mq',
    shortTitle: 'blk-mq',
    summary: 'Linux block multi-queue layer이며 bio를 request로 바꿔 hardware queue로 보냅니다.',
    position: communitySlot('foundation', 1, 0),
    sourceKeys: ['notionPart3', 'localKernel'],
    visual: blkMqStructureVisual,
    plain: 'blk-mq는 block I/O를 여러 hardware queue에 나눠 제출하는 block layer 구조입니다.',
    why: 'DPAS hook은 결국 blk-mq polling 경로 어딘가에 붙습니다.',
    context: 'block/bio.c, block/blk-mq.c, NVMe driver path를 잇는 중심축입니다.',
  },
  {
    id: 'concept-ctx',
    kind: '개념',
    status: '확정',
    community: 'foundation',
    title: 'software context (ctx)',
    shortTitle: 'ctx',
    summary: 'per-CPU software queue이며 op flag에 따라 ctx->hctxs[]로 hctx를 고릅니다.',
    position: communitySlot('foundation', 2, 0),
    sourceKeys: ['localKernel', 'notionPart3'],
    visual: ctxVisual,
    plain: 'blk_mq_ctx는 submit CPU에 붙은 software queue context입니다.',
    why: 'ctx와 hctx를 구분해야 queue mapping과 DPAS state 위치를 올바르게 잡을 수 있습니다.',
    context: 'block/blk-mq.h의 blk_mq_map_queue(opf, ctx)가 ctx->hctxs[type]을 반환합니다.',
    confusions: ['ctx는 CPU-side, hctx는 hardware queue-side입니다.', 'ctx 1개가 hctx 1개와 같지 않습니다.'],
  },
  {
    id: 'concept-mq-ops',
    kind: '개념',
    status: '확정',
    community: 'foundation',
    title: 'mq_ops driver callbacks',
    shortTitle: 'mq_ops',
    summary: 'queue_rq / poll / complete callback으로 block layer와 driver를 연결합니다.',
    position: communitySlot('foundation', 3, 0),
    sourceKeys: ['localKernel', 'notionPart3'],
    visual: mqOpsVisual,
    plain: 'blk_mq_ops는 driver가 구현하는 callback table입니다.',
    why: 'submit/poll/interrupt completion 경계를 mq_ops 기준으로 봐야 hook 위치를 비교할 수 있습니다.',
    context: 'NVMe PCI는 nvme_queue_rq와 nvme_poll을 등록합니다 (drivers/nvme/host/pci.c).',
  },
  {
    id: 'concept-bio',
    kind: '개념',
    status: '확정',
    community: 'foundation',
    title: 'bio',
    shortTitle: 'bio',
    summary: 'block layer로 들어오는 I/O 단위이며 poll 가능 여부와 cookie를 들고 있습니다.',
    position: communitySlot('foundation', 0, 1),
    sourceKeys: ['notionStep1'],
    visual: bioVisual,
    plain: 'bio는 block I/O 요청의 기본 단위입니다. polled I/O에서는 bio->bi_cookie가 중요합니다.',
    why: 'bio_poll()은 bio에서 cookie를 읽고 poll 가능 여부를 결정합니다.',
    context: 'Step 1에서 bio_poll()의 입력 객체로 등장합니다.',
    confusions: ['bio는 device driver에 바로 제출되는 최종 단위가 아닙니다.', 'bi_cookie는 request tag가 아닙니다.'],
  },
  {
    id: 'concept-request',
    kind: '개념',
    status: '잠정',
    community: 'foundation',
    title: 'request',
    shortTitle: 'request',
    summary: 'driver에 제출되는 blk-mq 요청 단위입니다.',
    position: communitySlot('foundation', 1, 1),
    sourceKeys: ['notionPart3'],
    visual: requestVisual,
    plain: 'request는 blk-mq가 driver에 넘기는 제출 단위입니다.',
    why: 'request가 어떤 hctx에 묶였는지가 나중에 bi_cookie 저장으로 이어집니다.',
    context: 'blk_mq_start_request()에서 request와 bio cookie 연결이 보입니다.',
  },
  {
    id: 'concept-hctx',
    kind: '개념',
    status: '확정',
    community: 'foundation',
    title: 'hardware context (hctx)',
    shortTitle: 'hctx',
    summary: 'blk-mq의 hardware queue context이며 queue_num이 poll cookie가 됩니다.',
    position: communitySlot('foundation', 2, 1),
    sourceKeys: ['notionStep1', 'localKernel'],
    visual: hctxVisual,
    plain: 'hctx는 blk-mq가 hardware queue를 다루기 위해 쓰는 per-queue context입니다.',
    why: 'bi_cookie는 hctx->queue_num이므로 hctx를 모르면 cookie 의미를 오해합니다.',
    context: 'blk_mq_poll()은 cookie로 q->queue_hw_ctx[cookie]를 찾습니다.',
    confusions: ['hctx는 CPU 자체가 아니라 hardware queue context입니다.', 'hctx->queue_num은 request tag가 아닙니다.'],
  },
  {
    id: 'concept-req-polled',
    kind: '개념',
    status: '잠정',
    community: 'foundation',
    title: 'REQ_POLLED',
    shortTitle: 'REQ_POLLED',
    summary: '이 I/O가 polling completion 경로를 쓴다는 request flag입니다.',
    position: communitySlot('foundation', 3, 1),
    sourceKeys: ['notionPart3', 'notionPart6'],
    visual: reqPolledVisual,
    plain: 'REQ_POLLED가 설정된 I/O는 interrupt 대신 poll queue completion을 기대합니다.',
    why: 'true interrupt mode는 이 flag와 queue selection까지 봐야 합니다.',
    context: 'Part 6에서 completion-path skip만으로 충분한지 의심하는 핵심입니다.',
  },
  {
    id: 'concept-bi-cookie-tag',
    kind: '오해',
    status: '확정',
    community: 'foundation',
    title: 'bi_cookie는 tag가 아니다',
    shortTitle: 'cookie != tag',
    summary: 'bi_cookie는 hctx queue index이고, tag는 hctx 내부 request slot입니다.',
    position: communitySlot('foundation', 4, 1),
    sourceKeys: ['notionStep1'],
    visual: cookieTagVisual,
    plain: 'bi_cookie = hctx->queue_num입니다. tag는 request slot이라 의미가 다릅니다.',
    why: '이걸 틀리면 blk_mq_poll(q, cookie)가 왜 hctx를 찾는지 이해할 수 없습니다.',
    context: 'Step 1에서 가장 먼저 정정한 오해입니다.',
    confusions: ['bi_cookie = tag(7) 같은 식으로 읽으면 안 됩니다.', '초기값 BLK_QC_T_NONE(-1)은 poll 불가라는 뜻입니다.'],
  },
];
