import type { CardDraft } from '../types';
import { communitySlot } from '../layout';
import { bioPollVisual, blkHctxPollVisual, blkMqPollVisual, interruptCompletionVisual, ioUringIopollVisual, nvmePollVisual, pollPathVisual, startRequestVisual, submitPathVisual } from '../visuals';

export const step1PollingCards: CardDraft[] = [
  {
    id: 'path-io-uring-iopoll',
    kind: '현재 작업',
    status: '확정',
    community: 'step1-polling',
    title: 'io_uring IOPOLL path',
    shortTitle: 'io_uring IOPOLL',
    summary: 'IORING_SETUP_IOPOLL -> IOCB_HIPRI -> REQ_POLLED -> iocb_bio_iopoll -> bio_poll() 경로입니다.',
    position: communitySlot('step1-polling', 0, 0),
    sourceKeys: ['localKernel', 'notionStep1'],
    visual: ioUringIopollVisual,
    plain: 'io_uring IOPOLL은 userspace polled I/O 의도가 kernel block poll path로 들어오는 대표 경로입니다.',
    why: 'FIO io_uring 실험과 REQ_POLLED submit-side 제어(Part 6)를 이해하려면 이 진입점이 필요합니다.',
    context: 'io_uring/rw.c, block/fops.c, block/blk-core.c iocb_bio_iopoll()을 잇습니다.',
  },
  {
    id: 'path-submit-polled',
    kind: '현재 작업',
    status: '잠정',
    community: 'step1-polling',
    title: 'Submit path for polled I/O',
    shortTitle: 'submit path',
    summary: 'I/O가 device로 나가기 전 request/hctx/cookie가 정해지는 경로입니다.',
    position: communitySlot('step1-polling', 1, 0),
    sourceKeys: ['notionStep1', 'localKernel'],
    visual: submitPathVisual,
    plain: 'submit 시점은 I/O를 block layer/driver 쪽으로 실제 제출하기 위해 request를 시작하는 시점입니다.',
    why: 'poll path만 보면 bi_cookie가 어디서 생겼는지 놓칩니다.',
    context: 'blk_mq_start_request()에서 bio->bi_cookie가 저장됩니다.',
  },
  {
    id: 'function-blk-mq-start-request',
    kind: '모듈',
    status: '확정',
    community: 'step1-polling',
    title: 'blk_mq_start_request()',
    shortTitle: 'start_request',
    summary: 'driver issue 시점에 polled bio의 bi_cookie = hctx->queue_num을 저장합니다.',
    position: communitySlot('step1-polling', 2, 0),
    sourceKeys: ['localKernel', 'notionStep1'],
    visual: startRequestVisual,
    plain: 'blk_mq_start_request()는 cookie가 생기는 정확한 함수입니다.',
    why: 'submit vs poll 경계에서 cookie 생성 시점을 이 함수로 고정해야 합니다.',
    context: 'block/blk-mq.c:1368-1393, REQ_POLLED bio만 bi_cookie를 WRITE_ONCE합니다.',
  },
  {
    id: 'path-poll-completion',
    kind: '현재 작업',
    status: '잠정',
    community: 'step1-polling',
    title: 'Poll completion path',
    shortTitle: 'poll path',
    summary: 'bio_poll()에서 시작해 blk_mq_poll(), blk_hctx_poll(), nvme_poll()로 내려가는 완료 확인 경로입니다.',
    position: communitySlot('step1-polling', 0, 1),
    sourceKeys: ['notionStep1', 'notionPart3'],
    visual: pollPathVisual,
    plain: 'poll 시점은 완료 interrupt를 기다리지 않고 CPU가 completion queue를 직접 확인하는 시점입니다.',
    why: 'PAS sleep-before-poll hook 후보는 이 경로에서 찾아야 합니다.',
    context: 'Part 3 Step 1의 핵심 코드 리딩 경로입니다.',
  },
  {
    id: 'path-interrupt-completion',
    kind: '현재 작업',
    status: '확정',
    community: 'step1-polling',
    title: 'Interrupt completion path',
    shortTitle: 'IRQ completion',
    summary: 'IRQ -> blk_mq_complete_request() -> mq_ops->complete() 또는 BLOCK_SOFTIRQ 경로입니다.',
    position: communitySlot('step1-polling', 3, 0),
    sourceKeys: ['localKernel', 'notionPart3'],
    visual: interruptCompletionVisual,
    plain: 'REQ_POLLED 없는 I/O는 interrupt/softirq completion path로 끝납니다.',
    why: 'polled path와 대칭으로 알아야 DPAS interrupt mode가 바꿔야 할 지점을 구분할 수 있습니다.',
    context: 'block/blk-mq.c blk_mq_complete_request()와 NVMe IRQ handler가 연결됩니다.',
  },
  {
    id: 'function-bio-poll',
    kind: '모듈',
    status: '잠정',
    community: 'step1-polling',
    title: 'bio_poll()',
    shortTitle: 'bio_poll',
    summary: 'bio->bi_cookie를 읽고 BLK_QC_T_NONE이면 poll을 하지 않습니다.',
    position: communitySlot('step1-polling', 1, 1),
    sourceKeys: ['notionStep1'],
    visual: bioPollVisual,
    plain: 'bio_poll()은 poll entry입니다. cookie가 없으면 바로 0을 반환합니다.',
    why: '초기값 -1이면 poll 불가라는 문장이 여기서 의미를 갖습니다.',
    context: 'block/bio.c 쪽 polling entry로 읽습니다.',
  },
  {
    id: 'function-blk-mq-poll',
    kind: '모듈',
    status: '잠정',
    community: 'step1-polling',
    title: 'blk_mq_poll()',
    shortTitle: 'blk_mq_poll',
    summary: 'cookie로 queue_hw_ctx를 찾아 hctx polling으로 넘깁니다.',
    position: communitySlot('step1-polling', 2, 1),
    sourceKeys: ['notionStep1'],
    visual: blkMqPollVisual,
    plain: 'blk_mq_poll(q, cookie)는 q->queue_hw_ctx[cookie]로 hctx를 찾습니다.',
    why: 'cookie가 hctx index라는 사실이 여기서 직접 쓰입니다.',
    context: 'block/blk-mq.c의 poll dispatch 단계입니다.',
  },
  {
    id: 'function-blk-hctx-poll',
    kind: '모듈',
    status: '잠정',
    community: 'step1-polling',
    title: 'blk_hctx_poll()',
    shortTitle: 'blk_hctx_poll',
    summary: 'hctx의 mq_ops->poll()을 반복 호출하고 cpu_relax()를 사용합니다.',
    position: communitySlot('step1-polling', 3, 1),
    sourceKeys: ['notionStep1'],
    visual: blkHctxPollVisual,
    plain: 'blk_hctx_poll()은 driver poll callback을 부르는 block layer polling loop입니다.',
    why: 'cpu_relax()는 PAS sleep이 아니므로 이 함수의 loop를 잘못 해석하면 안 됩니다.',
    context: 'PAS hook 후보와 cpu_relax 오해가 만나는 지점입니다.',
  },
  {
    id: 'function-nvme-poll',
    kind: '모듈',
    status: '잠정',
    community: 'step1-polling',
    title: 'nvme_poll()',
    shortTitle: 'nvme_poll',
    summary: 'NVMe poll queue의 completion queue를 확인하는 driver callback입니다.',
    position: communitySlot('step1-polling', 4, 1),
    sourceKeys: ['notionPart3', 'localKernel'],
    visual: nvmePollVisual,
    plain: 'nvme_poll()은 block layer mq_ops->poll() 아래의 NVMe driver 구현입니다.',
    why: 'DPAS가 실제 device completion을 어디서 확인하는지 끝단을 잡아줍니다.',
    context: 'drivers/nvme/host 경로의 poll callback 후보입니다.',
  },
];
