import type { CardDraft } from '../types';
import { communitySlot } from '../layout';
import { reqPolledSubmitStep2Visual, step2DpasComparisonVisual, step2FlagPropagationVisual, step2HookCandidatesVisual, step2KiocbHipriVisual } from '../visuals';

export const step2SubmissionCards: CardDraft[] = [
  {
    id: 'step2-req-polled-submission',
    kind: '현재 작업',
    status: '확정',
    community: 'step2-submission',
    title: 'Step 2 REQ_POLLED submission map',
    shortTitle: 'Step 2 map',
    summary: 'poll request가 만들어지는 submission path를 여러 세부 카드로 나눠 읽는 지도입니다.',
    position: communitySlot('step2-submission', 0, 0),
    sourceKeys: ['notionStep2', 'localKernel'],
    visual: reqPolledSubmitStep2Visual,
    plain: 'Step 2는 poll completion path가 아니라 poll request가 만들어지는 submission path를 추적합니다.',
    why: '한 카드에 몰아넣지 않고 signal, flag propagation, DPAS 비교, hook 후보로 나눠야 포팅 판단이 선명합니다.',
    context: '현재 src/linux-upstream 7.1.0-rc4와 DPAS 5.18 artifact를 비교하는 Step 2 출발 카드입니다.',
  },
  {
    id: 'step2-kiocb-hipri',
    kind: '개념',
    status: '확정',
    community: 'step2-submission',
    title: 'Step 2: RWF_HIPRI와 kiocb',
    shortTitle: 'RWF/kiocb',
    summary: 'userspace RWF_HIPRI가 kernel 내부의 kiocb->ki_flags / IOCB_HIPRI로 들어오는 지점입니다.',
    position: communitySlot('step2-submission', 1, 0),
    sourceKeys: ['notionStep2', 'localKernel'],
    visual: step2KiocbHipriVisual,
    plain: 'kiocb는 kernel 내부의 I/O 요청 설명서이고, ki_flags에 IOCB_HIPRI가 들어갑니다.',
    why: 'IOCB_HIPRI 조건을 이해해야 REQ_POLLED가 왜 붙는지 알 수 있습니다.',
    context: 'include/uapi/linux/fs.h, include/linux/fs.h, block/fops.c의 조건식을 연결합니다.',
  },
  {
    id: 'step2-flag-propagation',
    kind: '개념',
    status: '확정',
    community: 'step2-submission',
    title: 'Step 2: bio->request flag propagation',
    shortTitle: 'flag flow',
    summary: 'bio->bi_opf의 REQ_POLLED가 data.cmd_flags와 rq->cmd_flags로 전파되어 HCTX_TYPE_POLL을 고릅니다.',
    position: communitySlot('step2-submission', 2, 0),
    sourceKeys: ['notionStep2', 'localKernel'],
    visual: step2FlagPropagationVisual,
    plain: 'REQ_POLLED는 bio에서 request로 복사되고, queue type 선택에 직접 쓰입니다.',
    why: 'completion path만 보아서는 이미 poll hctx로 routing된 future I/O를 설명할 수 없습니다.',
    context: 'block/fops.c, block/blk-mq.c, block/blk-mq.h, blk_mq_start_request()를 잇는 카드입니다.',
  },
  {
    id: 'step2-dpas-518-comparison',
    kind: '개념',
    status: '확정',
    community: 'step2-submission',
    title: 'Step 2: DPAS 5.18 interrupt 비교',
    shortTitle: '5.18 compare',
    summary: 'DPAS 5.18은 interrupt mode에서 IOCB_HIPRI와 REQ_POLLED를 submission path에서 제거했습니다.',
    position: communitySlot('step2-submission', 1, 1),
    sourceKeys: ['notionStep2', 'localKernel'],
    visual: step2DpasComparisonVisual,
    plain: 'DPAS 5.18의 interrupt mode는 polled I/O를 만든 뒤 poll만 안 하는 방식이 아니었습니다.',
    why: '현재 src에 같은 policy가 없으므로 migration에서 submit-side hook을 다시 설계해야 합니다.',
    context: 'kernel/block/fops.c와 kernel/fs/iomap/direct-io.c의 interrupt enforcement를 현재 src와 비교합니다.',
  },
  {
    id: 'step2-hook-candidates',
    kind: '현재 작업',
    status: '검증 필요',
    community: 'step2-submission',
    title: 'Step 2: submission hook 후보',
    shortTitle: 'hook 후보',
    summary: 'REQ_POLLED 생성 제어 후보는 block/fops.c와 fs/iomap/direct-io.c로 나눠 봅니다.',
    position: communitySlot('step2-submission', 2, 1),
    sourceKeys: ['notionStep2', 'localKernel'],
    visual: step2HookCandidatesVisual,
    plain: 'raw block DIO와 filesystem DIO는 서로 다른 submit path를 탑니다.',
    why: '실험 workload가 어느 경로를 타는지에 따라 interrupt-mode hook coverage가 달라집니다.',
    context: 'Part 6 full interrupt mode와 Part 4 PAS-only 범위를 분리하는 기준 카드입니다.',
  },
];
