import type { CardDraft } from '../types';
import { communitySlot } from '../layout';
import {
  step4HctxTypeMapVisual,
  step4OpenQuestionsVisual,
  step4OverviewVisual,
  step4PollHookCandidatesVisual,
  step4QueueLifecycleVisual,
  step4RequestQueueModelVisual,
  step4StatePlacementVisual,
  step4SysfsLifecycleVisual,
} from '../visuals';

export const step4DiffDecisionCards: CardDraft[] = [
  {
    id: 'step4-overview',
    kind: '현재 작업',
    status: '확정',
    community: 'step4-diff-decision',
    title: 'Step 4: diff, state, hook decision',
    shortTitle: 'Step 4 map',
    summary: 'Step 4는 Part 4 구현 전에 state 위치, poll hook 후보, sysfs lifecycle 순서를 먼저 고정하는 단계입니다.',
    position: communitySlot('step4-diff-decision', 0, 0),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4OverviewVisual,
    plain: '이 카드는 Step 4가 처음에는 구현 전 decision note였지만, 지금은 최신 dpas-kernel 코드 상태를 따라가야 한다는 점을 설명합니다. Step 1-3에서 확인한 poll/submit path 위에 실제 submit helper, request_queue direct field, switch_enabled reset, mode switching static test가 올라왔습니다.',
    why: 'learning tree가 예전 계획 상태에 머물면 현재 코드가 어디서 REQ_POLLED를 바꾸고 어디서 mode를 전환하는지 놓치게 됩니다. Step 4는 이제 "구현 후보"보다 "현재 코드 변경을 읽는 지도" 역할을 해야 합니다.',
    context: 'history/2026-06-15.md는 request_queue direct field full DPAS, blk_dpas_prepare_bio(), switch_enabled reset, full_mode_switching_static.py를 최신 기준으로 정리합니다. history/2026-06-17.md는 그 코드가 bzImage까지 빌드됐지만 runtime boot는 남았다고 정리합니다.',
    confusions: [
      'Step 4를 아직 구현 전 계획으로만 읽으면 현재 코드 변경을 놓칩니다.',
      'poll queue mapping을 새로 만드는 문제가 아니라 이미 HCTX_TYPE_POLL로 들어온 I/O와 submit helper의 REQ_POLLED 제어를 함께 읽는 문제입니다.',
    ],
    next: ['state placement 카드에서 최신 direct field 구조를 봅니다.', 'DPAS policy의 submit helper 카드에서 실제 REQ_POLLED 제어 경로를 확인합니다.'],
  },
  {
    id: 'step4-state-placement',
    kind: '현재 작업',
    status: '확정',
    community: 'step4-diff-decision',
    title: 'Step 4: request_queue state placement',
    shortTitle: 'state 위치',
    summary: '현재 dpas-kernel은 request_queue에 full DPAS mode/counter/QD/tf/switch_param 필드를 직접 두는 방식으로 구현되어 있습니다.',
    position: communitySlot('step4-diff-decision', 1, 0),
    sourceKeys: ['history20260615', 'localKernel'],
    visual: step4StatePlacementVisual,
    plain: '이 카드는 최신 구현의 state 위치를 설명합니다. enum dpas_mode는 struct request_queue 밖에 있고, request_queue 안에는 dpas_lock, dpas_mode, mode별 counter, QD/tf 표본, switch_enabled, switch_param1~7이 직접 들어 있습니다.',
    why: '현재 코드를 읽을 때 가장 먼저 볼 것은 "state를 어디에 둘까"가 아니라 "state가 이미 queue에 어떤 이름으로 들어갔나"입니다. submit helper, sysfs reset, poll-time switcher가 모두 이 queue state를 공유합니다.',
    context: 'dpas-kernel/include/linux/blkdev.h:490-554가 최신 field 배치를 보여 줍니다. history/2026-06-15.md는 enum dpas_mode 이동, dpas_mode 타입 변경, direct-field 설계에 맞춘 static test 갱신을 기록합니다.',
    confusions: [
      '이 카드는 미래 리팩터링 방향을 닫는 카드가 아니라 현재 코드 상태를 읽기 위한 카드입니다.',
      'mode counter는 completion path가 아니라 submit helper에서 증가하는 값도 있습니다.',
      'QD/tf 표본은 poll/PAS sleep 경로에서 모이므로 submit counter와 섞어 읽으면 안 됩니다.',
    ],
    next: ['sysfs lifecycle 카드에서 switch_enabled가 이 state window를 어떻게 reset하는지 봅니다.', 'mode switching direct field 카드에서 submit/sysfs/poll이 같은 state를 어떻게 공유하는지 확인합니다.'],
  },
  {
    id: 'step4-poll-hook-candidates',
    kind: '현재 작업',
    status: '잠정',
    community: 'step4-diff-decision',
    title: 'Step 4: poll hook candidates',
    shortTitle: 'hook 후보',
    summary: 'bio_poll, blk_mq_poll, blk_hctx_poll, nvme_poll을 비교하고 blk_mq_poll()을 1차 PAS hook 후보로 둡니다.',
    position: communitySlot('step4-diff-decision', 2, 0),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4PollHookCandidatesVisual,
    plain: '이 카드는 PAS sleep-before-poll hook을 어느 poll 계층에 둘지 설명합니다. latest path는 bio_poll()이 cookie를 읽고 blk_mq_poll()을 호출하며, blk_mq_poll()은 q->queue_hw_ctx[cookie]로 hctx를 찾아 blk_hctx_poll()로 넘깁니다.',
    why: 'blk_mq_poll()은 bio_poll()보다 blk-mq 내부에 가깝고, blk_hctx_poll()보다 policy hook으로 너무 낮지 않으며, nvme_poll()보다 장치 독립적입니다. 다만 request-level bucket이나 중복 update guard를 얻을 방법은 아직 검증해야 합니다.',
    context: 'latest src/linux-upstream/block/blk-core.c:942-971, block/blk-mq.c:5250-5274, drivers/nvme/host/pci.c:1666-1680과 old kernel/block/blk-mq.c:5377-5407, 5857-5865를 비교합니다.',
    confusions: [
      'blk_mq_poll()이 1순위 후보라는 말은 최종 확정이라는 뜻이 아닙니다. request-level 정보가 막히면 후보를 다시 비교해야 합니다.',
      'nvme_poll()은 실제 CQ와 가깝지만 NVMe 전용이므로 block layer 공통 PAS hook과는 성격이 다릅니다.',
    ],
    next: ['open questions 카드에서 blk_mq_poll() 후보가 닫아야 할 request-level gap을 봅니다.', 'Part 4 Minimal PAS 카드에서 실제 hook patch 순서로 내려갑니다.'],
  },
  {
    id: 'step4-sysfs-lifecycle',
    kind: '개념',
    status: '확정',
    community: 'step4-diff-decision',
    title: 'Step 4: switch_enabled reset lifecycle',
    shortTitle: 'sysfs 순서',
    summary: '현재 switch_enabled sysfs store는 값을 쓰는 동시에 mode/counter/QD/tf window를 PAS 기준으로 reset합니다.',
    position: communitySlot('step4-diff-decision', 3, 0),
    sourceKeys: ['history20260615', 'localKernel'],
    visual: step4SysfsLifecycleVisual,
    plain: '이 카드는 현재 switch_enabled sysfs 동작을 설명합니다. store callback은 queue가 DPAS poll-capable인지 확인하고, 0/1 값을 parse한 뒤 dpas_lock 안에서 switch_enabled를 쓰고 queue_dpas_reset_switch_state()로 mode와 counter window를 새로 시작합니다.',
    why: 'switch_enabled는 단순 on/off knob가 아니라 새 측정 window의 시작점입니다. reset을 lock 밖에서 하거나 counter 일부만 남기면 submit helper와 poll switcher가 서로 다른 window를 보게 됩니다.',
    context: 'dpas-kernel/block/blk-sysfs.c:788-831이 reset helper와 show/store 본문이고, line 925와 1141이 sysfs entry 등록입니다. history/2026-06-15.md는 이 reset 이유를 한국어 주석으로 보강했다고 기록합니다.',
    confusions: [
      'switch_enabled=1은 이전 counter를 이어서 켜는 것이 아니라 PAS 기준 새 window를 시작합니다.',
      'sysfs show/store는 사용자 인터페이스지만 여기서는 submit/poll hot path state와 같은 lock을 공유합니다.',
      'pas_enabled와 switch_enabled는 같은 의미가 아닙니다. 전자는 PAS sleep 경로, 후자는 full mode switching gate입니다.',
    ],
    next: ['queue lifecycle 카드에서 direct field 초기값과 reset 위치를 확인합니다.', 'full mode switching static test 카드에서 sysfs reset이 어떤 token으로 검증되는지 봅니다.'],
  },
  {
    id: 'step4-queue-lifecycle',
    kind: '개념',
    status: '확정',
    community: 'step4-diff-decision',
    title: 'Step 4: request_queue DPAS init/reset lifecycle',
    shortTitle: 'queue lifecycle',
    summary: '현재 구현은 request_queue 생성 시 direct DPAS fields를 초기화하고, switch_enabled store 때 mode window를 reset합니다.',
    position: communitySlot('step4-diff-decision', 0, 1),
    sourceKeys: ['history20260615', 'localKernel'],
    visual: step4QueueLifecycleVisual,
    plain: '이 카드는 최신 구현의 lifecycle을 설명합니다. 별도 state allocation/free 후보를 고르는 단계가 아니라, blk_mq_init_allocated_queue() 흐름에서 dpas_lock, switch_enabled, dpas_mode, counters, QD/tf를 초기화하고 sysfs write 때 다시 reset하는 구조입니다.',
    why: '현재 코드의 lifecycle 질문은 "어디서 할당하나"보다 "초기값과 reset window가 언제 보장되나"입니다. 이걸 알아야 static test와 runtime sysfs 검증을 같은 기준으로 읽을 수 있습니다.',
    context: 'dpas-kernel/block/blk-mq.c:4777-4786은 DPAS direct fields 초기화를 보여 주고, block/blk-sysfs.c:788-831은 switch_enabled reset window를 보여 줍니다.',
    confusions: [
      '초기화와 reset은 다릅니다. 초기화는 queue 생성 시 기본값이고 reset은 사용자가 switch_enabled를 다시 쓸 때 새 측정 window를 여는 일입니다.',
      'direct field 방식은 allocation 실패 경로를 줄이지만 request_queue 구조체 자체에 실험 state가 들어간다는 tradeoff가 있습니다.',
      'runtime 검증에서는 초기값뿐 아니라 switch_enabled를 여러 번 썼을 때 counter가 재시작되는지도 봐야 합니다.',
    ],
    next: ['sysfs lifecycle 카드에서 reset이 lock 안에서 일어나는 이유를 봅니다.', 'full mode switching static test 카드에서 queue 초기화와 reset 검사가 어떻게 묶였는지 확인합니다.'],
  },
  {
    id: 'step4-request-queue-model',
    kind: '개념',
    status: '확정',
    community: 'step4-diff-decision',
    title: 'Step 4: request_queue contains ctx and hctx',
    shortTitle: 'q 안의 ctx/hctx',
    summary: 'request_queue *q는 queue 하나의 주소지만 q 안에는 per-CPU ctx와 여러 hardware hctx가 있습니다.',
    position: communitySlot('step4-diff-decision', 1, 1),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4RequestQueueModelVisual,
    plain: '이 카드는 request_queue를 단일 list가 아니라 blk-mq 상태 묶음으로 읽는 법을 설명합니다. q에는 mq_ops, per-CPU queue_ctx, nr_hw_queues, queue_hw_ctx 배열이 들어 있고, 여러 blk_mq_ctx가 같은 blk_mq_hw_ctx를 가리킬 수 있습니다.',
    why: 'queue에 DPAS state를 둔다는 말은 특정 request 하나가 아니라 block device queue 단위로 mode/counter/QD/tf를 보관한다는 뜻입니다. poll path에서는 cookie가 q->queue_hw_ctx[cookie] index로 쓰이므로 q와 hctx의 경계를 분리해서 봐야 합니다.',
    context: 'latest src/linux-upstream/include/linux/blkdev.h:493-511은 mq_ops, queue_ctx, queue_hw_ctx를 보여 주고, src/linux-upstream/block/blk-mq.h:20-29는 ctx가 hctxs[HCTX_MAX_TYPES]를 가진다는 것을 보여 줍니다.',
    confusions: [
      'request_queue 하나가 hctx 하나라는 뜻은 아닙니다. q 하나 안에 여러 hctx가 있고 cookie가 그중 하나를 고릅니다.',
      'block device가 늘어나면 request_queue도 보통 늘지만, partition은 parent disk의 queue를 공유할 수 있습니다.',
    ],
    next: ['hctx type map 카드에서 DEFAULT/READ/POLL type별 hctx 선택 규칙을 봅니다.', 'poll hook 후보 카드에서 q->queue_hw_ctx[cookie]가 왜 중요한지 다시 확인합니다.'],
  },
  {
    id: 'step4-hctx-type-init-map',
    kind: '개념',
    status: '확정',
    community: 'step4-diff-decision',
    title: 'Step 4: DEFAULT/READ/POLL map timing',
    shortTitle: 'hctx type map',
    summary: 'DEFAULT/READ/POLL queue map은 init 때 준비되고 request 때 REQ_POLLED/READ flag로 선택됩니다.',
    position: communitySlot('step4-diff-decision', 2, 1),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4HctxTypeMapVisual,
    plain: '이 카드는 mq queue가 request 때 새로 만들어지는 것이 아니라 init 때 용도별 map으로 준비된 뒤 request 때 선택된다는 점을 설명합니다. blk_mq_get_hctx_type()은 REQ_POLLED를 먼저 보고 POLL type을 고르고, 그 다음 READ이면 READ type을 고릅니다.',
    why: 'Part 4 PAS-only는 poll queue 자체를 새로 만드는 작업이 아닙니다. 이미 HCTX_TYPE_POLL로 들어온 request에 sleep-before-poll policy와 duration update를 얹는 작업입니다.',
    context: 'latest src/linux-upstream/include/linux/blk-mq.h:482-503은 hctx_type과 map 주석이고, block/blk-mq.h:90-113은 blk_mq_get_hctx_type()과 blk_mq_map_queue(), block/blk-mq.c:553은 request-time lookup입니다.',
    confusions: [
      'READ queue는 read latency를 write-heavy workload에서 보호하기 위한 분리이고, PAS-only의 직접 대상은 REQ_POLLED가 선택하는 POLL queue입니다.',
      'polled read는 READ queue가 아니라 POLL queue가 우선입니다. REQ_POLLED 검사가 READ 검사보다 먼저 오기 때문입니다.',
    ],
    next: ['request_queue model 카드로 돌아가 ctx->hctxs[type] 구조를 확인합니다.', 'open questions 카드에서 Part 4 구현 전에 남은 gap을 확인합니다.'],
  },
  {
    id: 'step4-open-questions',
    kind: '미해결',
    status: '검증 필요',
    community: 'step4-diff-decision',
    title: 'Step 4: questions after current full DPAS patch',
    shortTitle: '남은 질문',
    summary: '현재 full DPAS 코드는 static/build를 통과했지만 VM boot, runtime sysfs, 실제 HIPRI I/O 검증은 아직 남아 있습니다.',
    position: communitySlot('step4-diff-decision', 3, 1),
    sourceKeys: ['history20260615', 'history20260617', 'localKernel'],
    visual: step4OpenQuestionsVisual,
    plain: '이 카드는 최신 코드 이후 남은 검증 질문을 모읍니다. 핵심은 새 bzImage가 VM에서 부팅되는지, switch_enabled와 mode knobs가 runtime에서 동작하는지, HIPRI direct I/O가 submit helper와 poll switcher를 실제로 타는지입니다.',
    why: 'static test와 bzImage build는 중요한 진전이지만 DPAS가 실제 workload에서 의도한 mode로 움직인다는 증거는 아닙니다. 다음 tree 업데이트는 compile evidence와 runtime evidence를 분리해 추적해야 합니다.',
    context: 'history/2026-06-15.md는 full_mode_switching_static.py와 전체 커널 빌드 통과를 기록했고, history/2026-06-17.md는 Docker/Colima로 bzImage 생성까지 통과했지만 VM boot와 runtime I/O는 남았다고 기록합니다.',
    confusions: [
      'build 통과는 boot 통과와 다릅니다.',
      'sysfs knob가 보이는 것과 실제 HIPRI I/O가 mode 전이를 타는 것은 다릅니다.',
      'FIO IOPS 차이만으로 mode switching이 맞다고 결론 내리면 안 됩니다. counter/trace 근거가 필요합니다.',
    ],
    next: ['Colima build loop 카드에서 현재 빌드 검증 경계를 확인합니다.', 'Optane knob reset 카드에서 성능 측정 전에 mode 상태를 고정하는 이유를 봅니다.'],
  },
];
