import type { CardDraft } from '../types';
import { communitySlot } from '../layout';
import {
  step4HctxTypeMapVisual,
  step4OpenQuestionsVisual,
  step4OverviewVisual,
  step4PollHookCandidatesVisual,
  step4QueueLifecycleVisual,
  step4RequestQueueModelVisual,
  step4StatePlacementVisual,
  step4SysfsLifecycleVisual,
} from '../visuals';

export const step4DiffDecisionCards: CardDraft[] = [
  {
    id: 'step4-overview',
    kind: '현재 작업',
    status: '확정',
    community: 'step4-diff-decision',
    title: 'Step 4: diff, state, hook decision',
    shortTitle: 'Step 4 map',
    summary: 'Step 4는 Part 4 구현 전에 state 위치, poll hook 후보, sysfs lifecycle 순서를 먼저 고정하는 단계입니다.',
    position: communitySlot('step4-diff-decision', 0, 0),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4OverviewVisual,
    plain: '이 카드는 Step 4가 왜 코드 작성 단계가 아니라 결정 단계인지 설명합니다. Step 1-3에서 확인한 poll path와 old DPAS hook inventory를 바탕으로, Part 4에서 처음 만질 위치와 아직 미룰 범위를 나눕니다.',
    why: 'Part 4를 바로 쓰기 시작하면 request_queue state, poll hook, sysfs knob가 서로 의존해서 수정 순서가 꼬입니다. Step 4는 q->dpas 구조와 blk_mq_poll() 후보를 먼저 좁혀 수동 구현 순서를 만들게 해 줍니다.',
    context: 'Notion Step 4는 latest src/linux-upstream/block/blk-core.c:942, block/blk-mq.c:5269, block/blk-sysfs.c:590, kernel/block/blk-mq.c:5857을 비교한 decision note입니다.',
    confusions: [
      'Step 4는 DPAS 기능을 구현하는 단계가 아니라 Part 4 구현 전에 어느 구조를 건드릴지 결정하는 단계입니다.',
      'poll queue mapping을 새로 만드는 문제가 아니라 이미 HCTX_TYPE_POLL로 들어온 I/O 위에 PAS policy를 얹는 문제입니다.',
    ],
    next: ['state placement 카드에서 request_queue 직접 field 복사를 피하는 이유를 봅니다.', 'poll hook 후보 카드에서 blk_mq_poll()을 1차 후보로 두는 근거를 확인합니다.'],
  },
  {
    id: 'step4-state-placement',
    kind: '현재 작업',
    status: '잠정',
    community: 'step4-diff-decision',
    title: 'Step 4: request_queue state placement',
    shortTitle: 'state 위치',
    summary: 'old DPAS field를 request_queue에 그대로 복사하지 않고 struct dpas_queue *dpas pointer로 분리하는 판단입니다.',
    position: communitySlot('step4-diff-decision', 1, 0),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4StatePlacementVisual,
    plain: '이 카드는 PAS/DPAS state를 최신 request_queue 어디에 둘지 설명합니다. old DPAS는 pas_stat, pas_enabled, switch_enabled 같은 field를 request_queue에 직접 넣었지만, 최신 이식에서는 request_queue에 pointer 하나를 두고 실제 state를 struct dpas_queue 아래로 모으는 방향이 더 안전합니다.',
    why: 'q->dpas 방식은 PAS-only와 full DPAS mode switching을 분리하고, CONFIG_DPAS 격리와 allocation/free 처리를 명확하게 만듭니다. sysfs와 poll hook도 모두 q->dpas NULL guard를 공통 전제로 삼을 수 있습니다.',
    context: 'old kernel/include/linux/blkdev.h:424-444에는 pas_stat, pas_enabled, switch_enabled가 직접 들어 있고, latest src/linux-upstream/include/linux/blkdev.h:484-511에는 mq_ops, queue_ctx, queue_hw_ctx만 보이며 DPAS state는 없습니다.',
    confusions: [
      'request_queue에 pointer를 하나 추가하는 것과 old DPAS field 전체를 복사하는 것은 유지보수 비용이 다릅니다.',
      'q->dpas를 쓰면 항상 존재한다고 가정할 수 없습니다. 모든 사용 지점에서 allocation 실패와 CONFIG_DPAS=n 경로를 생각해야 합니다.',
    ],
    next: ['queue lifecycle 카드에서 q->dpas를 어디서 할당하고 해제할지 봅니다.', 'sysfs lifecycle 카드에서 q->dpas NULL handling이 왜 먼저 필요한지 확인합니다.'],
  },
  {
    id: 'step4-poll-hook-candidates',
    kind: '현재 작업',
    status: '잠정',
    community: 'step4-diff-decision',
    title: 'Step 4: poll hook candidates',
    shortTitle: 'hook 후보',
    summary: 'bio_poll, blk_mq_poll, blk_hctx_poll, nvme_poll을 비교하고 blk_mq_poll()을 1차 PAS hook 후보로 둡니다.',
    position: communitySlot('step4-diff-decision', 2, 0),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4PollHookCandidatesVisual,
    plain: '이 카드는 PAS sleep-before-poll hook을 어느 poll 계층에 둘지 설명합니다. latest path는 bio_poll()이 cookie를 읽고 blk_mq_poll()을 호출하며, blk_mq_poll()은 q->queue_hw_ctx[cookie]로 hctx를 찾아 blk_hctx_poll()로 넘깁니다.',
    why: 'blk_mq_poll()은 bio_poll()보다 blk-mq 내부에 가깝고, blk_hctx_poll()보다 policy hook으로 너무 낮지 않으며, nvme_poll()보다 장치 독립적입니다. 다만 request-level bucket이나 중복 update guard를 얻을 방법은 아직 검증해야 합니다.',
    context: 'latest src/linux-upstream/block/blk-core.c:942-971, block/blk-mq.c:5250-5274, drivers/nvme/host/pci.c:1666-1680과 old kernel/block/blk-mq.c:5377-5407, 5857-5865를 비교합니다.',
    confusions: [
      'blk_mq_poll()이 1순위 후보라는 말은 최종 확정이라는 뜻이 아닙니다. request-level 정보가 막히면 후보를 다시 비교해야 합니다.',
      'nvme_poll()은 실제 CQ와 가깝지만 NVMe 전용이므로 block layer 공통 PAS hook과는 성격이 다릅니다.',
    ],
    next: ['open questions 카드에서 blk_mq_poll() 후보가 닫아야 할 request-level gap을 봅니다.', 'Part 4 Minimal PAS 카드에서 실제 hook patch 순서로 내려갑니다.'],
  },
  {
    id: 'step4-sysfs-lifecycle',
    kind: '개념',
    status: '잠정',
    community: 'step4-diff-decision',
    title: 'Step 4: sysfs after q->dpas lifecycle',
    shortTitle: 'sysfs 순서',
    summary: 'pas_enabled sysfs knob는 q->dpas 구조와 init/free 위치가 정해진 뒤에 구현해야 안전합니다.',
    position: communitySlot('step4-diff-decision', 3, 0),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4SysfsLifecycleVisual,
    plain: '이 카드는 sysfs를 왜 세 번째로 봐야 하는지 설명합니다. old DPAS는 q->pas_enabled를 직접 읽고 썼지만, q->dpas pointer 구조에서는 show/store가 q->dpas->pas_enabled에 접근하기 전에 NULL 여부와 lifetime을 확인해야 합니다.',
    why: 'sysfs knob를 먼저 만들면 q->dpas가 아직 없거나 이미 free된 상태를 건드릴 위험이 있습니다. 따라서 q->dpas 구조, init/free, NULL guard가 먼저 정해져야 pas_enabled show/store를 안전하게 붙일 수 있습니다.',
    context: 'latest src/linux-upstream/block/blk-sysfs.c:590-595는 QUEUE_RW_ENTRY macro 패턴이고, line 734부터 queue_attrs 배열에 attribute entry를 넣는 구조입니다. old kernel/block/blk-sysfs.c:61-88은 q->pas_enabled 직접 show/store를 사용했습니다.',
    confusions: [
      '.show와 .store는 함수 이름에 suffix를 기대하는 문법이 아니라 구조체 field입니다. _prefix##_show, _prefix##_store가 매크로에서 함수 이름을 만들어냅니다.',
      'sysfs_emit()은 사용자에게 직접 출력하는 함수가 아니라 show callback의 page buffer를 안전하게 채우는 helper입니다.',
    ],
    next: ['queue lifecycle 카드에서 q->dpas allocation/free 후보 위치를 먼저 확인합니다.', 'state placement 카드로 돌아가 q->dpas NULL guard를 poll hook에도 적용합니다.'],
  },
  {
    id: 'step4-queue-lifecycle',
    kind: '개념',
    status: '잠정',
    community: 'step4-diff-decision',
    title: 'Step 4: request_queue lifecycle for q->dpas',
    shortTitle: 'queue lifecycle',
    summary: 'blk_alloc_queue(), blk_mq_alloc_queue(), blk_free_queue()를 읽어 q->dpas allocation/free 후보를 잡습니다.',
    position: communitySlot('step4-diff-decision', 0, 1),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4QueueLifecycleVisual,
    plain: '이 카드는 q->dpas를 언제 만들고 언제 해제할지 설명합니다. blk_alloc_queue()는 request_queue 객체 자체를 만들고, blk_mq_alloc_queue() wrapper는 blk_mq_init_allocated_queue() 성공까지 묶어서 blk-mq queue를 완성합니다.',
    why: 'PAS는 poll path에 붙는 기능이므로 hctx/tag/context가 준비된 뒤 state를 붙이는 편이 자연스럽습니다. free는 request_queue 메모리가 RCU callback으로 넘어가기 전에 q->dpas를 해제하는 방향을 검토해야 합니다.',
    context: 'latest src/linux-upstream/block/blk-core.c:393-423은 blk_alloc_queue(), block/blk-mq.c:4440-4461은 blk_mq_alloc_queue(), block/blk-core.c:257-267은 blk_free_queue()입니다.',
    confusions: [
      'struct request_queue *blk_alloc_queue에서 *는 함수 이름에 붙은 것이 아니라 request_queue 주소를 반환한다는 뜻입니다.',
      'q pointer 하나가 request_queue 하나를 가리키지만, 그 request_queue 안에는 여러 ctx와 hctx가 들어갈 수 있습니다.',
    ],
    next: ['request_queue model 카드에서 q 하나 안에 ctx/hctx가 어떻게 들어 있는지 봅니다.', 'sysfs lifecycle 카드에서 allocation 실패와 NULL handling을 show/store에 반영합니다.'],
  },
  {
    id: 'step4-request-queue-model',
    kind: '개념',
    status: '확정',
    community: 'step4-diff-decision',
    title: 'Step 4: request_queue contains ctx and hctx',
    shortTitle: 'q 안의 ctx/hctx',
    summary: 'request_queue *q는 queue 하나의 주소지만 q 안에는 per-CPU ctx와 여러 hardware hctx가 있습니다.',
    position: communitySlot('step4-diff-decision', 1, 1),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4RequestQueueModelVisual,
    plain: '이 카드는 request_queue를 단일 list가 아니라 blk-mq 상태 묶음으로 읽는 법을 설명합니다. q에는 mq_ops, per-CPU queue_ctx, nr_hw_queues, queue_hw_ctx 배열이 들어 있고, 여러 blk_mq_ctx가 같은 blk_mq_hw_ctx를 가리킬 수 있습니다.',
    why: 'q->dpas에 state를 둔다는 말은 특정 request 하나가 아니라 block device queue 단위로 PAS state를 보관한다는 뜻입니다. poll path에서는 cookie가 q->queue_hw_ctx[cookie] index로 쓰이므로 q와 hctx의 경계를 분리해서 봐야 합니다.',
    context: 'latest src/linux-upstream/include/linux/blkdev.h:493-511은 mq_ops, queue_ctx, queue_hw_ctx를 보여 주고, src/linux-upstream/block/blk-mq.h:20-29는 ctx가 hctxs[HCTX_MAX_TYPES]를 가진다는 것을 보여 줍니다.',
    confusions: [
      'request_queue 하나가 hctx 하나라는 뜻은 아닙니다. q 하나 안에 여러 hctx가 있고 cookie가 그중 하나를 고릅니다.',
      'block device가 늘어나면 request_queue도 보통 늘지만, partition은 parent disk의 queue를 공유할 수 있습니다.',
    ],
    next: ['hctx type map 카드에서 DEFAULT/READ/POLL type별 hctx 선택 규칙을 봅니다.', 'poll hook 후보 카드에서 q->queue_hw_ctx[cookie]가 왜 중요한지 다시 확인합니다.'],
  },
  {
    id: 'step4-hctx-type-init-map',
    kind: '개념',
    status: '확정',
    community: 'step4-diff-decision',
    title: 'Step 4: DEFAULT/READ/POLL map timing',
    shortTitle: 'hctx type map',
    summary: 'DEFAULT/READ/POLL queue map은 init 때 준비되고 request 때 REQ_POLLED/READ flag로 선택됩니다.',
    position: communitySlot('step4-diff-decision', 2, 1),
    sourceKeys: ['notionStep4', 'localKernel'],
    visual: step4HctxTypeMapVisual,
    plain: '이 카드는 mq queue가 request 때 새로 만들어지는 것이 아니라 init 때 용도별 map으로 준비된 뒤 request 때 선택된다는 점을 설명합니다. blk_mq_get_hctx_type()은 REQ_POLLED를 먼저 보고 POLL type을 고르고, 그 다음 READ이면 READ type을 고릅니다.',
    why: 'Part 4 PAS-only는 poll queue 자체를 새로 만드는 작업이 아닙니다. 이미 HCTX_TYPE_POLL로 들어온 request에 sleep-before-poll policy와 duration update를 얹는 작업입니다.',
    context: 'latest src/linux-upstream/include/linux/blk-mq.h:482-503은 hctx_type과 map 주석이고, block/blk-mq.h:90-113은 blk_mq_get_hctx_type()과 blk_mq_map_queue(), block/blk-mq.c:553은 request-time lookup입니다.',
    confusions: [
      'READ queue는 read latency를 write-heavy workload에서 보호하기 위한 분리이고, PAS-only의 직접 대상은 REQ_POLLED가 선택하는 POLL queue입니다.',
      'polled read는 READ queue가 아니라 POLL queue가 우선입니다. REQ_POLLED 검사가 READ 검사보다 먼저 오기 때문입니다.',
    ],
    next: ['request_queue model 카드로 돌아가 ctx->hctxs[type] 구조를 확인합니다.', 'open questions 카드에서 Part 4 구현 전에 남은 gap을 확인합니다.'],
  },
  {
    id: 'step4-open-questions',
    kind: '미해결',
    status: '검증 필요',
    community: 'step4-diff-decision',
    title: 'Step 4: questions before Part 4 patch',
    shortTitle: '남은 질문',
    summary: 'blk_mq_poll() 후보와 q->dpas 방향을 Part 4 patch로 바꾸기 전에 닫아야 할 확인 질문입니다.',
    position: communitySlot('step4-diff-decision', 3, 1),
    sourceKeys: ['notionStep4', 'notionPart4', 'localKernel'],
    visual: step4OpenQuestionsVisual,
    plain: '이 카드는 지금 바로 코드를 쓰기 전에 닫아야 할 질문을 모읍니다. 핵심은 blk_mq_poll()에서 request-level 정보를 충분히 얻을 수 있는지, q->dpas allocation 실패와 NULL handling을 어떻게 처리할지, old DPAS의 중복 sleep/update guard를 최신 구조에 어떻게 옮길지입니다.',
    why: '이 질문이 닫히면 사용자가 직접 작성할 Part 4 patch 순서를 안정적으로 줄 수 있습니다. 반대로 request lookup이나 duration update 위치가 불명확한 상태에서 sleep만 넣으면 PAS가 아니라 고정 delay 실험이 됩니다.',
    context: 'Notion Step 4의 마지막 체크리스트는 request-level 정보, RQF_MQ_POLL_SLEPT 같은 guard, q->dpas init/free, sysfs pas_enabled safety를 Part 4 이전 확인 항목으로 둡니다.',
    confusions: [
      '남은 질문이 많다는 것은 Step 4가 실패했다는 뜻이 아닙니다. Part 4 patch의 위험 지점을 미리 드러낸 것입니다.',
      'sleep-before-poll hook만 있으면 PAS가 끝난다고 보면 안 됩니다. result update와 중복 방지까지 있어야 최소 PAS에 가까워집니다.',
    ],
    next: ['Part 4 Minimal PAS-only port 카드에서 구현 task로 내려갑니다.', '필요하면 blk_mq_poll()에서 request를 다시 찾는 방법을 별도 코드리딩 카드로 추가합니다.'],
  },
];
