import type { CardDraft } from '../types';
import { communitySlot } from '../layout';
import {
  step3DpasHookInventoryVisual,
  step3InterruptFopsVisual,
  step3NvmeQueueVisual,
  step3OverviewVisual,
  step3Part4BoundaryVisual,
  step3PasSleepUpdateVisual,
  step3PasStateVisual,
  step3QueueMappingVisual,
} from '../visuals';

export const step3QueueHookCards: CardDraft[] = [
  {
    id: 'step3-overview',
    kind: '현재 작업',
    status: '확정',
    community: 'step3-queue-hooks',
    title: 'Step 3: Queue Mapping + DPAS hook map',
    shortTitle: 'Step 3 map',
    summary: 'Step 3는 최신 poll queue foundation과 DPAS 5.18 hook inventory를 분리해서 Part 4 범위를 정하는 단계입니다.',
    position: communitySlot('step3-queue-hooks', 0, 0),
    sourceKeys: ['notionStep3', 'localKernel'],
    visual: step3OverviewVisual,
    plain: 'Step 3는 Step 1/2에서 본 polling path와 REQ_POLLED 흐름을 바탕으로, 실제 queue mapping과 DPAS 5.18의 추가 hook을 카테고리별로 나눕니다.',
    why: 'poll queue 구조와 PAS policy를 섞으면 Part 4에서 불필요하게 NVMe queue mapping까지 건드리게 됩니다.',
    context: 'Notion Step 3는 최신 src/linux-upstream 7.1.0-rc4와 kernel/5.18.0-rc6-dpas-fast26 artifact를 나란히 읽은 결과입니다.',
    confusions: [
      'Step 3가 Step 2와 같은 말처럼 보이는 이유는 REQ_POLLED/HCTX_TYPE_POLL 용어가 반복되기 때문입니다.',
      'Step 3의 새 내용은 "flag가 붙는다"가 아니라 "flag가 어떤 queue map으로 이어지고 DPAS가 그 위에 무엇을 추가했는가"입니다.',
    ],
    next: ['queue mapping foundation 카드를 읽어 request allocation 시점의 hctx 선택을 확인합니다.', 'DPAS hook inventory 카드에서 실제 이식 후보와 제외 범위를 분리합니다.'],
  },
  {
    id: 'step3-queue-mapping-foundation',
    kind: '개념',
    status: '확정',
    community: 'step3-queue-hooks',
    title: 'Step 3: REQ_POLLED -> HCTX_TYPE_POLL mapping',
    shortTitle: 'queue map',
    summary: '최신 kernel에서 REQ_POLLED가 request allocation 시 HCTX_TYPE_POLL hctx를 선택하는 구조입니다.',
    position: communitySlot('step3-queue-hooks', 1, 0),
    sourceKeys: ['notionStep3', 'localKernel'],
    visual: step3QueueMappingVisual,
    plain: 'REQ_POLLED가 bio/request flag에 있으면 blk_mq_get_hctx_type()이 HCTX_TYPE_POLL을 반환하고, blk_mq_map_queue()가 ctx->hctxs[HCTX_TYPE_POLL]을 선택합니다.',
    why: 'queue type 선택은 poll loop가 아니라 request allocation 시점에 결정되므로, full interrupt mode를 completion path만으로 만들 수 없습니다.',
    context: 'src/linux-upstream/include/linux/blk-mq.h:481-493, block/blk-mq.h:90-113, block/blk-mq.c:551-553이 핵심 근거입니다.',
    confusions: [
      'READ 요청이면 READ queue로 갈 것 같지만 READ | REQ_POLLED이면 POLL queue가 우선입니다.',
      'bio_poll()에서 poll 여부가 처음 정해지는 것이 아니라 submit/request allocation 전에 이미 방향이 정해집니다.',
    ],
    next: ['NVMe poll queue 카드에서 HCTX_TYPE_POLL이 실제 driver queue map으로 어떻게 연결되는지 봅니다.', 'interrupt fops hook 카드에서 REQ_POLLED 제거가 왜 submission-side 문제인지 확인합니다.'],
  },
  {
    id: 'step3-nvme-poll-queue-map',
    kind: '개념',
    status: '확정',
    community: 'step3-queue-hooks',
    title: 'Step 3: NVMe poll queue mapping',
    shortTitle: 'NVMe poll map',
    summary: 'NVMe poll queue는 default/read queue와 별도이고, IRQ affinity 없이 generic CPU mapping을 사용합니다.',
    position: communitySlot('step3-queue-hooks', 2, 0),
    sourceKeys: ['notionStep3', 'localKernel'],
    visual: step3NvmeQueueVisual,
    plain: 'NVMe PCI driver는 poll_queues = min(dev->nr_poll_queues, nr_io_queues - 1)로 poll queue 수를 정하고, HCTX_TYPE_POLL map에는 IRQ affinity 대신 blk_mq_map_queues()를 씁니다.',
    why: 'poll queue가 여러 개일 수 있다는 사실을 알아야 PAS state를 CPU별/queue별로 어디에 둘지 판단할 수 있습니다.',
    context: 'src/linux-upstream/drivers/nvme/host/pci.c:681-708, 2898-2903과 block/blk-mq-cpumap.c:59-77이 근거입니다.',
    confusions: [
      'poll queue가 하나만 있다고 가정하면 CPU 분산과 per-CPU PAS state를 잘못 이해하게 됩니다.',
      'poll queue는 IRQ가 없으므로 interrupt vector affinity와 같은 기준으로 보면 안 됩니다.',
    ],
    next: ['DPAS hook inventory 카드에서 5.18 artifact가 이 queue foundation 위에 어떤 policy를 얹었는지 봅니다.', 'Part 4 boundary 카드에서 NVMe queue mapping을 당장 수정하지 않는 이유를 확인합니다.'],
  },
  {
    id: 'step3-dpas-518-hook-inventory',
    kind: '개념',
    status: '확정',
    community: 'step3-queue-hooks',
    title: 'Step 3: DPAS 5.18 hook inventory',
    shortTitle: '5.18 hooks',
    summary: 'DPAS 5.18이 추가한 PAS/DPAS state, sysfs, sleep, result update, mode switching hook 목록입니다.',
    position: communitySlot('step3-queue-hooks', 3, 0),
    sourceKeys: ['notionStep3', 'localKernel'],
    visual: step3DpasHookInventoryVisual,
    plain: 'DPAS 5.18 artifact는 HCTX_TYPE_POLL 구조 자체를 새로 만든 것이 아니라, request_queue field, per-CPU pas_stat, blk_switch, sysfs knob, sleep-before-poll, result update를 추가했습니다.',
    why: '이 hook inventory가 있어야 Part 4에서 가져올 최소 PAS subset과 Part 5/6으로 미룰 full DPAS subset을 분리할 수 있습니다.',
    context: 'kernel/include/linux/blk_types.h, blkdev.h, blk-mq.h, kernel/block/blk-sysfs.c, kernel/block/blk-mq.c를 묶어 읽는 카드입니다.',
    confusions: [
      'DPAS 5.18 변경을 blk_mq_poll_hybrid_sleep() 하나로 줄이면 state와 update 경로를 놓칩니다.',
      'pas_enabled와 switch_enabled는 같은 범위가 아닙니다. 전자는 PAS-only에 가깝고, 후자는 full DPAS mode switching입니다.',
    ],
    next: ['PAS state 카드에서 blk_rq_pas_stat이 어떤 feedback loop를 만드는지 봅니다.', 'interrupt fops hook 카드에서 full DPAS interrupt mode가 submission path에 걸리는 이유를 확인합니다.'],
  },
  {
    id: 'step3-pas-state-duration',
    kind: '개념',
    status: '확정',
    community: 'step3-queue-hooks',
    title: 'Step 3: PAS state and duration feedback',
    shortTitle: 'PAS state',
    summary: 'blk_rq_pas_stat의 dur, adj, sr_last, update_req, dur_cnt가 다음 sleep duration을 만드는 feedback loop입니다.',
    position: communitySlot('step3-queue-hooks', 0, 1),
    sourceKeys: ['notionStep3', 'localKernel'],
    visual: step3PasStateVisual,
    plain: 'PAS는 dur 하나만 저장하지 않습니다. 최근 sleep result 두 개와 update flag, duration generation counter를 함께 써서 다음 sleep 시간을 계산합니다.',
    why: 'sleep-before-poll만 이식하고 result feedback을 빼면 논문 PAS가 아니라 단순 고정 지연이 됩니다.',
    context: 'kernel/include/linux/blk_types.h:536-548와 kernel/block/blk-mq.c:5255-5283의 duration update 코드가 연결됩니다.',
    confusions: [
      'sr_last 값 자체보다 중요한 것은 "sleep 결과를 다음 duration 계산에 반영한다"는 구조입니다.',
      'dur_cnt는 성능 조정값이 아니라 request 결과를 중복 반영하지 않기 위한 generation 추적값입니다.',
    ],
    next: ['sleep/update loop 카드에서 이 state가 언제 읽히고 언제 갱신되는지 시간 순서로 봅니다.', 'Part 4 boundary 카드에서 state placement를 request_queue 직접 field가 아니라 dpas_queue로 감싸는 이유를 확인합니다.'],
  },
  {
    id: 'step3-pas-sleep-update-loop',
    kind: '개념',
    status: '확정',
    community: 'step3-queue-hooks',
    title: 'Step 3: PAS sleep-before-poll and result update',
    shortTitle: 'sleep/update',
    summary: 'blk_mq_poll_hybrid_sleep()가 sleep하고, blk_mq_poll_classic()이 poll 결과를 다음 duration update에 반영합니다.',
    position: communitySlot('step3-queue-hooks', 1, 1),
    sourceKeys: ['notionStep3', 'localKernel'],
    visual: step3PasSleepUpdateVisual,
    plain: 'PAS path는 blk_mq_poll_pas_nsecs()로 sleep 시간을 계산하고, hrtimer_sleeper + io_schedule()로 CPU를 양보한 뒤, poll_count 결과로 sr_last/update_req를 갱신합니다.',
    why: 'Part 4에서 실제로 이식해야 하는 핵심은 queue mapping이 아니라 이 sleep/update loop입니다.',
    context: 'kernel/block/blk-mq.c:5378-5594의 sleep-before-poll과 5659-5852의 result update를 한 세트로 읽습니다.',
    confusions: [
      'io_schedule() sleep만 넣으면 PAS가 아닙니다. 다음 duration을 바꾸는 update path가 같이 있어야 합니다.',
      'cpu_relax()는 PAS sleep이 아닙니다. PAS sleep은 scheduler에 CPU를 양보합니다.',
    ],
    next: ['Part 4 Minimal PAS 카드에서 최신 kernel의 어느 poll entry에 이 loop를 재구성할지 판단합니다.', 'DPAS hook inventory 카드로 돌아가 sysfs와 state 초기화가 어디서 연결되는지 봅니다.'],
  },
  {
    id: 'step3-dpas-interrupt-fops-hook',
    kind: '개념',
    status: '확정',
    community: 'step3-queue-hooks',
    title: 'Step 3: DPAS interrupt mode fops.c hook',
    shortTitle: 'fops IRQ hook',
    summary: 'DPAS 5.18 interrupt mode는 bio_poll()을 생략하는 수준이 아니라 submit 전에 IOCB_HIPRI/REQ_POLLED를 제거합니다.',
    position: communitySlot('step3-queue-hooks', 2, 1),
    sourceKeys: ['notionStep3', 'localKernel'],
    visual: step3InterruptFopsVisual,
    plain: 'kernel/block/fops.c에서 sc->mode가 interrupt이면 iocb->ki_flags &= ~IOCB_HIPRI, bio.bi_opf &= ~REQ_POLLED를 수행한 뒤 submit_bio()로 보냅니다.',
    why: '이 코드는 Step 3의 중요한 보정입니다. full DPAS interrupt mode의 hook은 completion path가 아니라 submission path에 걸려 있었습니다.',
    context: 'kernel/block/fops.c:110-147과 164-174를 보면 polled mode는 bio_poll(), interrupt mode는 blk_io_schedule()로 갈라집니다.',
    confusions: [
      'bio_poll()을 호출하지 않는 것만으로 true interrupt mode가 되는 것이 아닙니다.',
      'REQ_POLLED를 submit 전에 제거해야 HCTX_TYPE_POLL 선택 자체를 피할 수 있습니다.',
    ],
    next: ['Step 2 submission hook 후보 카드와 연결해서 최신 kernel에서도 같은 coverage가 가능한지 봅니다.', 'Part 6 Full Interrupt Mode 카드에서 filesystem DIO/iomap path까지 검증 범위를 넓힙니다.'],
  },
  {
    id: 'step3-part4-boundary',
    kind: '현재 작업',
    status: '잠정',
    community: 'step3-queue-hooks',
    title: 'Step 3: Part 4 boundary decision',
    shortTitle: 'Part 4 경계',
    summary: 'Step 3의 결론은 queue mapping을 새로 만들지 않고 최신 poll path 위에 PAS-only policy만 최소 이식하는 것입니다.',
    position: communitySlot('step3-queue-hooks', 3, 1),
    sourceKeys: ['notionStep3', 'notionPart4', 'localKernel'],
    visual: step3Part4BoundaryVisual,
    plain: 'Part 4에서는 HCTX_TYPE_POLL, NVMe poll queue allocation, IRQ affinity 제외 branch를 건드리지 않고, PAS sleep-before-poll과 duration/result update만 먼저 이식하는 쪽이 안전합니다.',
    why: 'queue mapping과 full interrupt mode까지 동시에 건드리면 build failure, hang, latency regression의 원인을 분리하기 어렵습니다.',
    context: 'Step 3의 hook inventory는 Part 4 PAS-only, Part 5 mode switching, Part 6 interrupt submission hook으로 나누는 기준입니다.',
    confusions: [
      'poll queue 구조가 Step 3에 길게 설명되어 있어도, 그것은 이식 대상이라는 뜻이 아니라 이미 있으니 건드리지 말자는 근거입니다.',
      'fops.c interrupt hook은 중요하지만 Part 4 PAS-only의 첫 구현 범위에서는 제외하는 것이 좋습니다.',
    ],
    next: ['Part 4 Minimal PAS-only port 카드에서 실제 구현 task로 내려갑니다.', 'Step 4 diff/hook 평가에서 최신 kernel 함수 위치가 5.18과 얼마나 다른지 확인합니다.'],
  },
];
